import ETH from "../../assets/images/ETH.png";
import MetaBet from "../../assets/images/MetaBet.png";
import WETH from "../../assets/images/WETH.svg";
import USDT from "../../assets/images/USDT.svg";
import BUSD from "../../assets/images/BUSD.png";
import BNB from "../../assets/images/BNB.svg";
import ETC from "../../assets/images/ETC.svg";
import MATIC from "../../assets/images/MATIC.svg";
import GOAL from "../../assets/images/GOAL.png";
export const TabTableData = [
  {
    id: 1,
    name: "METABET",
    odds: 1.2,
    poolSize: "000.00",
    img: MetaBet,
    amount: "Amount",
    pool: "Pool Total",
    odd: "Odds",
    win: "Possible WIN",
  },
  {
    id: 2,
    name: "ETH",
    odds: 1.25,
    poolSize: "000.00",
    img: ETH,
    amount: "Amount",
    pool: "Pool Total",
    odd: "Odds",
    win: "Possible WIN",
  },
  {
    id: 3,
    name: "BNB",
    odds: 1.11,
    poolSize: "000.00",
    img: BNB,
    amount: "Amount",
    pool: "Pool Total",
    odd: "Odds",
    win: "Possible WIN",
  },
  {
    id: 4,
    name: "BUSD",
    odds: 1.5,
    poolSize: "000.00",
    img: BUSD,
    amount: "Amount",
    pool: "Pool Total",
    odd: "Odds",
    win: "Possible WIN",
  },
  {
    id: 5,
    name: "USDT",
    odds: 1.28,
    poolSize: "000.00",
    img: USDT,
    amount: "Amount",
    pool: "Pool Total",
    odd: "Odds",
    win: "Possible WIN",
  },
  {
    id: 6,
    name: "WETH",
    odds: 1.32,
    poolSize: "000.00",
    img: WETH,
    amount: "Amount",
    pool: "Pool Total",
    odd: "Odds",
    win: "Possible WIN",
  },
  {
    id: 7,
    name: "MATIC",
    odds: 1.06,
    poolSize: "000.00",
    img: MATIC,
    amount: "Amount",
    pool: "Pool Total",
    odd: "Odds",
    win: "Possible WIN",
  },
  // {
  //   id: 8,
  //   name: "GOAL",
  //   odds: 1.42,
  //   poolSize: 192.42,
  //   img: GOAL,
  //   amount: "Amount",
  //   pool: "Pool Total",
  //   odd: "Odds",
  //   win: "Possible WIN",
  // },
  {
    id: 9,
    name: "ETC",
    odds: 1.46,
    poolSize: "000.00",
    img: ETC,
    amount: "Amount",
    pool: "Pool Total",
    odd: "Odds",
    win: "Possible WIN",
  },
];
