import React from "react";
import { TermsContainer } from "../Terms/Terms.styles";

const Privacy = () => {
  return (
    <>
      <TermsContainer>
        <span>Terms</span>
        <p>Privacy Policy</p>
        <div className="Content">
          <div className="headlines">
            <span>MetaBetmask.com</span>
            <span>Privacy Policy</span>
            <span>November 2022</span>
            <div className="text">
              <p>
                This Privacy Policy describes Our policies and procedures on the
                collection, use and disclosure of Your information when You{" "}
                <br /> use the Service and tells You about Your privacy rights
                and how the law protects You. <br />
                We use Your Personal data to provide and improve the Service. By
                using the Service, You agree to the collection and use of <br />{" "}
                information in accordance with this Privacy Policy. <br />
                Interpretation and Definitions <br />
                The words of which the initial letter is capitalized have
                meanings defined under the following conditions. The following{" "}
                <br /> definitions shall have the same meaning regardless of
                whether they appear in singular or in plural. <br />
                Definitions <br />
                For the purposes of this Cookies Policy: <br />
                1.1 “Account” means a unique account created for You to access
                our Service or parts of our Service. <br />
                1.2 “Affiliate” means an entity that controls, is controlled by
                or is under common control with a party, where "control" means{" "}
                <br /> ownership of 50% or more of the shares, equity interest
                or other securities entitled to vote for election of directors
                or other <br /> managing authority. <br />
                1.3 “Application” means the software program provided by the
                Company downloaded by You on any electronic device, named <br />{" "}
                metabetmask.
                <br />
                1.4 “Company” (referred to as either "the Company", "We", "Us"
                or "Our" in this Agreement) refers to MetaBetMask.com. <br />
                1.5 “Cookies” are small files that are placed on Your computer,
                mobile device or any other device by a website, containing the{" "}
                <br /> details of Your browsing history on that website among
                its many uses.
                <br />
                1.6 “Country” refers to: Costa Rica. <br />
                1.7 “Device” means any device that can access the Service such
                as a computer, a cellphone or a digital tablet. <br />
                1.8 “Personal Data” is any information that relates to an
                identified or identifiable individual. <br />
                1.9 “Service” refers to the Application or the Website or both.{" "}
                <br />
                1.10 “Service Provider” means any natural or legal person who
                processes the data on behalf of the Company. It refers to third-
                <br />
                party companies or individuals employed by the Company to
                facilitate the Service, to provide the Service on behalf of the{" "}
                <br /> Company, to perform services related to the Service or to
                assist the Company in analyzing how the Service is used. <br />
                1.11 “Usage Data” refers to data collected automatically, either
                generated by the use of the Service or from the Service <br />
                infrastructure itself (for example, the duration of a page
                visit).
                <br />
                1.12 “Website” refers to MetaBetMask, accessible from
                https://metabetmask.com/. <br />
                1.13 “You” means the individual accessing or using the Service,
                or the company, or other legal entity on behalf of which such
                <br /> individual is accessing or using the Service, as
                applicable.
              </p>
            </div>
          </div>
        </div>
      </TermsContainer>
    </>
  );
};

export default Privacy;
