import GOAL from "../../assets/images/Betimg/GOAL.png";
import BNB from "../../assets/images/Betimg/BNB.png";
import BUSD from "../../assets/images/Betimg/BUSD.png";
import busd from "../../assets/images/BUSD.png";
import metabet from "../../assets/images/metabet.webp";
import ETH from "../../assets/images/ETH.webp";
import USDT from "../../assets/images/usdt.webp";
import france from "../../assets/images/WorldcupBanner/france-mini.webp";
import poland from "../../assets/images/WorldcupBanner/poland-mini.webp";
import ChainLink from "../../assets/images/Betimg/chainlink.png";
import senegal from "../../assets/images/WorldcupBanner/senegal-mini.webp";
import england from "../../assets/images/WorldcupBanner/england-mini.webp";

export const betData = [
  {
    id: 1,
    icon1: BUSD,
    th_1: "Ticker",
    th_2: "Total Bets",
    th_3: "Bets Won",
    th_4: "Bets Lost",
    th_6: "Total Value",
    th_7: "Total Return",
    td_1: "BUSD",
    td_2: "0",
    td_3: "0",
    td_4: "0",
    td_5: "$0",
    td_6: "$0",
    th_5: "Chain Link",
    icon_2: ChainLink,
  },

  {
    id: 2,
    icon1: BNB,
    th_1: "Ticker",
    th_2: "Total Bets",
    th_3: "Bets Won",
    th_4: "Bets Lost",
    th_6: "Total Value",
    th_7: "Total Return",
    td_1: "BNB",
    td_2: "0",
    td_3: "0",
    td_4: "0",
    td_5: "$0",
    td_6: "$0",
    th_5: "Chain Link",
    icon_2: ChainLink,
  },
  {
    id: 3,
    icon1: GOAL,
    th_1: "Ticker",
    th_2: "Total Bets",
    th_3: "Bets Won",
    th_4: "Bets Lost",
    th_6: "Total Value",
    th_7: "Total Return",
    td_1: "GOAL",
    td_2: "0",
    td_3: "0",
    td_4: "0",
    td_5: "$0",
    td_6: "$0",
    th_5: "Chain Link",
    icon_2: ChainLink,
  },
  {
    id: 4,
    icon1: USDT,
    th_1: "Ticker",
    th_2: "Total Bets",
    th_3: "Bets Won",
    th_4: "Bets Lost",
    th_6: "Total Value",
    th_7: "Total Return",
    td_1: "USDT",
    td_2: "0",
    td_3: "0",
    td_4: "0",
    td_5: "$0",
    td_6: "$0",
    th_5: "Chain Link",
    icon_2: ChainLink,
  },

  {
    id: 5,
    icon1: ETH,
    th_1: "Ticker",
    th_2: "Total Bets",
    th_3: "Bets Won",
    th_4: "Bets Lost",
    th_6: "Total Value",
    th_7: "Total Return",
    td_1: "ETH",
    td_2: "0",
    td_3: "0",
    td_4: "0",
    td_5: "$0",
    td_6: "$0",
    th_5: "Chain Link",
    icon_2: ChainLink,
  },
  {
    id: 6,
    icon1: metabet,
    th_1: "Ticker",
    th_2: "Total Bets",
    th_3: "Bets Won",
    th_4: "Bets Lost",
    th_6: "Total Value",
    th_7: "Total Return",
    td_1: "METABET",
    td_2: "0",
    td_3: "0",
    td_4: "0",
    td_5: "$0",
    td_6: "$0",
    th_5: "Chain Link",
    icon_2: ChainLink,
  },
];

export const schedule = [
  {
    id: 1,
    date: "December 04 ,2022",
    time: "15:00 GMT",
    status: "LIVE",
    title1: "Senegal",
    title2: "England",
    draw: "Draw",
    icon: busd,
    backgroundColor: "#00AA25",
    btn_text: "Claim Win",
    bid: "BID:1",
    color: "#00AA25",
    win: "Won: 1.45",
    score1: "2.45",
    score2: "4.00",
    score3: "1.50",
    flag1: senegal,
    flag2: england,
    rectangle_color: "#081824",
  },
  {
    id: 2,
    date: "December 05 ,2022",
    time: "19:00 GMT",
    title1: "Poland",
    title2: "France",
    draw: "Draw",
    icon: busd,
    backgroundColor: "#00AA25",
    btn_text: "Claim Win",
    bid: "BID:1",
    color: "#FF0000 ",
    win: "Lost: 1.45",
    score1: "1.60",
    score2: "6.60",
    score3: "1.80",
    flag1: poland,
    flag2: france,
    rectangle_1_color: "#081824",
  },
  {
    id: 3,
    date: "December 04 ,2022",
    time: "15:00 GMT",
    status: "LIVE",
    title1: "Senegal",
    title2: "England",
    draw: "Draw",
    icon: busd,
    backgroundColor: "#FC4C1E",
    btn_text: "Claimed",
    bid: "BID:1",
    color: "#00AA25",
    win: "Won: 1.45",
    score1: "2.45",
    score2: "4.00",
    score3: "1.50",
    flag1: senegal,
    flag2: england,
    rectangle_color: "#081824",
  },
];
